Initial commit
01org/CODK-Tools pull request #1
Opened 2017-03-07 00:53 UTC by bigdinotech

-includes python script for generating .bin file that contains product
data section of OTP
-includes script for flashing .bin file int OTP section of flash using
JTAG

2017-03-07 00:53 UTC, bigdinotech commented
@SidLeung @eriknyquist please review
@noelpaz @russmcinnis please test

2017-03-09 23:02 UTC, bigdinotech commented
@eriknyquist please review
README will go on top of this commit
https://github.com/bigdinotech/CODK-Tools/tree/instructions_readme

2017-03-09 23:19 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    parser.add_argument('--product_sn', help="the product serial number, up to 16 ASCII characters", required=True)
"product" is superflous..... can you remove it from all the parameter names? i.e. --product-sn becomes --sn, or --serial

2017-03-09 23:22 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    parser.add_argument('--product_board_name', help="the product board name", required=True)
Let's use the expected conventions here, to be curteous to the user.

1) add short versions of each argument, i.e. "-v", "--hw-ver"
2) use a dash as a word separator (not underscore)

2017-03-09 23:23 UTC, bigdinotech commented on otp_provisioning/generate_factory_bin_product.py
> +    parser.add_argument('--product_sn', help="the product serial number, up to 16 ASCII characters", required=True)
I think we should keep it. That is from the original file. And really just added the parameters for VID/PID

2017-03-09 23:24 UTC, bigdinotech commented on otp_provisioning/generate_factory_bin_product.py
> +    parser.add_argument('--product_board_name', help="the product board name", required=True)
same as above.

2017-03-09 23:24 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    out_file = open("factory_data_product.bin", "wb")
Give it a name and stick it up top with MAGIC and VERSION....

2017-03-09 23:28 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    f = open('factory_data_product.cmd', 'w')
Same as the other filename...

2017-03-09 23:30 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +ARDUINO = "Arduino 101"
GENUINO and ARDUINO don't seem o be used anywhere....

2017-03-09 23:30 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +VENDOR = "Intel"
VENDOR is also not used anywhere

2017-03-09 23:32 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    print "Product S/N     : " + product_sn_padded
These seem like debug prints.... all the printing of the final padded values. Did you mean to remove them?

2017-03-09 23:33 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    assert len(args.product_sn) <= 16
Give them all names and put them up top. 4, 8, 16, 32, all of them

2017-03-09 23:37 UTC, eriknyquist requested changes
needs cleanup before it can be given to the general public...

2017-03-09 23:42 UTC, eriknyquist commented on otp_provisioning/generate_factory_bin_product.py
> +    parser.add_argument('--product_sn', help="the product serial number, up to 16 ASCII characters", required=True)
Yes, but up until now, this has been a private factory script. Now, we are making it public and giving it out to everyone; we can do better than this

2017-03-09 23:59 UTC, russmcinnis commented
I reviewed the instructions and they look clear enough for me. Nothing but the readme in there though.

2017-03-10 20:26 UTC, eriknyquist commented
closing. This is replaced by #2

2017-03-10 20:26 UTC, closed without merging